=== Gbyzzz/JavaWebDevelopment/task07webxmlparsing/target/classes/users.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://gbyzzz.by/task07webxmlparsing/entity/users"
        xmlns:tns="http://gbyzzz.by/task07webxmlparsing/entity/users"
        elementFormDefault="qualified" attributeFormDefault="unqualified">
    <element name = "users" >
        <complexType>
            <choice maxOccurs="unbounded">
                <element name = "user" type="tns:users" maxOccurs="unbounded"/>
                <element name = "admin" type="tns:users" maxOccurs="unbounded"/>
                <element name = "bartender" type="tns:users" maxOccurs="unbounded"/>
            </choice>
        </complexType>
        <unique name="unique-id">
            <selector xpath="user"/>
            <field xpath="@id"/>
        </unique>
        <unique name="unique-email">
            <selector xpath="user"/>
            <field xpath="@email"/>
        </unique>
        <unique name="unique-username">
            <selector xpath="user"/>
            <field xpath="@username"/>
        </unique>
        <unique name="unique-phone">
            <selector xpath="user"/>
            <field xpath="@phone"/>
        </unique>
    </element>
    <complexType name="users">
        <sequence>
            <element name="username">
                <simpleType>
                    <restriction base="string">
                        <pattern value="([a-zA-Z])[a-zA-Z0-9]{3,19}"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="phone" minOccurs="0" >
                <simpleType>
                    <restriction base="string">
                        <minLength value="10"/>
                        <maxLength value="12"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="email">
                <simpleType>
                    <restriction base="string">
                        <pattern value="[^@]+@[^\.]+\..+"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="is_active" type="boolean"/>
            <element name="reg_date" type="date"/>
        </sequence>
        <attribute name="id" type="long" use="required"/>
        <attribute name="name" type="string"/>
        <attribute name="surname" type="string"/>
    </complexType>
</schema>

=== Gbyzzz/JavaWebDevelopment/task07webxmlparsing/target/test-classes/users.xml
<?xml version="1.0" encoding="UTF-8"?>
<users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xlmns="http://gbyzzz.by/task07webxmlparsing"
         xsi:schemaLocation="http://gbyzzz.by/task07webxmlparsing users.xsd">
        <user id = "1" role = "Admin" name = "Tom" surname = "Smith">
            <username>Admin</username>
            <phone>08763856313</phone>
            <email>admin@bar.com</email>
            <is_active>true</is_active>
            <reg_date>2002-03-23</reg_date>
        </user>
        <user id = "2" role="Admin" name = "John" surname = "Cole">
            <username>Admin1</username>
            <phone>0689984689</phone>
            <email>admin1@bar.com</email>
            <is_active>true</is_active>
            <reg_date>2002-03-23</reg_date>
        </user>
        <user id = "3" role="Bartender" name = "Sam" surname = "Green">
            <username>LuckyBartender</username>
            <email>samgreen@bar.com</email>
            <is_active>true</is_active>
            <reg_date>2002-03-23</reg_date>
        </user>
        <user id = "4" role="User">
            <username>Jspm</username>
            <email>alcoholfan2010@gmail.com</email>
            <is_active>true</is_active>
            <reg_date>2002-03-23</reg_date>
        </user>
        <user id = "5" role="Bartender" name = "John">
            <username>JDaniels</username>
            <name>John</name>
            <email>jdaniels1985@yahoo.com</email>
            <is_active>true</is_active>
            <reg_date>2002-03-23</reg_date>
        </user>
        <user id = "6" role="User" name="Gabe">
            <username>Gmaster</username>
            <email>gmaster@gmail.com</email>
            <is_active>false</is_active>
            <reg_date>2002-03-23</reg_date>
        </user>
    </users>

=== Gbyzzz/JavaWebDevelopment/task07webxmlparsing/target/classes/users.xml
<?xml version="1.0" encoding="UTF-8"?>
<users xmlns:xsi="http://www.w3.org/2001/XMLSchema"
         xlmns="http://gbyzzz.by/task07webxmlparsing/entity"
         xsi:schemaLocation="http://gbyzzz.by/task07webxmlparsing/ users.xsd">
        <user id = "1" role = "Admin" name = "Tom" surname = "Smith">
            <username>Admin</username>
            <phone>08763856313</phone>
            <email>admin@bar.com</email>
            <is_active>true</is_active>
            <reg_date>2002-03-23</reg_date>
        </user>
        <user id = "2" role="Admin" name = "John" surname = "Cole">
            <username>Admin1</username>
            <phone>0689984689</phone>
            <email>admin1@bar.com</email>
            <is_active>true</is_active>
            <reg_date>2002-03-23</reg_date>
        </user>
        <user id = "3" role="Bartender" name = "Sam" surname = "Green">
            <username>LuckyBartender</username>
            <email>samgreen@bar.com</email>
            <is_active>true</is_active>
            <reg_date>2002-03-23</reg_date>
        </user>
        <user id = "4" role="User">
            <username>Jspm</username>
            <email>alcoholfan2010@gmail.com</email>
            <is_active>true</is_active>
            <reg_date>2002-03-23</reg_date>
        </user>
        <user id = "5" role="Bartender" name = "John">
            <username>JDaniels</username>
            <name>John</name>
            <email>jdaniels1985@yahoo.com</email>
            <is_active>true</is_active>
            <reg_date>2002-03-23</reg_date>
        </user>
        <user id = "6" role="User" name="Gabe">
            <username>Gmaster</username>
            <email>gmaster@gmail.com</email>
            <is_active>false</is_active>
            <reg_date>2002-03-23</reg_date>
        </user>
        <user id = "7" role="User" name="Julia">
            <username>SweetAndSour</username>
            <email>juli95@gmail.com</email>
            <is_active>true</is_active>
            <reg_date>2002-03-23</reg_date>
        </user>
        <user id = "8" role="Bartender" name="Dan">
            <username>DNegroni</username>
            <email>dnegroni@gmail.com</email>
            <is_active>false</is_active>
            <reg_date>2002-03-23</reg_date>
        </user>
        <user id = "9" role="User" name="Will" surname="Anderson">
            <username>WhiskeySour</username>
           <email>wa1984@gmail.com</email>
            <is_active>true</is_active>
            <reg_date>2002-03-23</reg_date>
        </user>
        <user id = "10" role="User" name="Ray">
            <username>RayWJ</username>
            <email>raywj@gmail.com</email>
            <is_active>true</is_active>
            <reg_date>2002-03-23</reg_date>
        </user>
        <user id = "11" role="Bartender" name="John">
            <username>TipsyBartender</username>
            <email>tipsybartender@gmail.com</email>
            <is_active>true</is_active>
            <reg_date>2002-03-23</reg_date>
        </user>
    </users>
